OOD_NOUNS = ['pen', 'book', 'computer', 'phone', 'table', 'chair', 'door', 'window', 'shirt', 'pants', 'shoe', 'bag',
             'wallet', 'glasses', 'watch', 'lamp', 'bed', 'sofa', 'television', 'radio', 'keyboard', 'mouse', 'brush',
             'bottle', 'key', 'clock', 'picture', 'frame', 'mirror', 'rug', 'curtain', 'pillow', 'blanket', 'cup',
             'spoon', 'plate', 'fork', 'knife', 'bucket', 'broom', 'towel', 'soap', 'shampoo', 'toothbrush',
             'toothpaste', 'hat', 'belt', 'scarf', 'glove', 'umbrella', 'bookshelf', 'drawer', 'wardrobe', 'bicycle',
             'motorcycle', 'bus', 'train', 'airplane', 'boat', 'camera', 'headphones', 'charger', 'battery', 'pencil',
             'eraser', 'notebook', 'stapler', 'tape', 'scissors', 'ruler', 'calculator', 'backpack', 'envelope',
             'stamp', 'mailbox', 'paper', 'marker', 'bin', 'trash bag', 'mop', 'sponge', 'bowl', 'tub', 'shower',
             'sink', 'faucet', 'toilet', 'refrigerator', 'oven', 'microwave', 'washing machine', 'dryer', 'dishwasher',
             'fan', 'heater', 'air conditioner', 'fireplace', 'vase', 'plant', 'flower', 'toy', 'doll', 'teddy bear',
             'ball', 'bat', 'racket', 'skateboard', 'helmet', 'puzzle', 'board game', 'card', 'candle', 'match',
             'lighter', 'nail', 'screw', 'hammer', 'wrench', 'saw', 'drill', 'ladder', 'rope', 'hose', 'can', 'jar',
             'box', 'bag', 'suitcase', 'trunk', 'guitar', 'piano', 'drum', 'trumpet', 'violin', 'flute', 'saxophone',
             'paintbrush', 'paint', 'canvas', 'easel', 'pot', 'pan', 'kettle', 'grill', 'stove', 'mixer', 'blender',
             'toaster', 'coffeemaker', 'juicer', 'scale', 'thermometer', 'compass', 'map', 'globe', 'flag', 'tent',
             'lantern', 'flashlight', 'magnifying glass', 'binoculars', 'telescope', 'camera', 'tripod', 'sd card',
             'usb drive', 'printer', 'scanner', 'fax machine', 'photocopier', 'telephone', 'answering machine',
             'stereo', 'cd player', 'mp3 player', 'speaker', 'microphone', 'headset', 'remote control', 'battery',
             'charger', 'outlet', 'plug', 'wire', 'cable', 'antenna', 'router', 'modem', 'laptop', 'tablet',
             'smartphone', 'desktop', 'monitor', 'keyboard', 'mouse', 'webcam', 'hard drive', 'disk', 'cd', 'dvd',
             'blu-ray', 'game console', 'joystick', 'gamepad', 'cartridge', 'controller', 'touch screen', 'stylus',
             'pen', 'pencil', 'marker', 'highlighter', 'crayon', 'chalk', 'eraser', 'sharpener', 'ruler', 'compass',
             'protractor', 'calculator', 'clipboard', 'notebook', 'binder', 'folder', 'portfolio', 'diary', 'calendar',
             'planner', 'agenda', 'post-it note', 'sticker', 'label', 'tape', 'glue', 'scissors', 'cutter', 'stapler',
             'hole punch', 'paper clip', 'rubber band', 'pin', 'tack', 'staple', 'brad', 'fastener', 'clip', 'clamp',
             'magnet', 'bookmark', 'divider', 'index card', 'flashcard', 'envelope', 'stationery', 'letter', 'postcard',
             'greeting card', 'invitation', 'announcement', 'flyer', 'brochure', 'pamphlet', 'poster', 'banner', 'sign',
             'billboard', 'menu', 'receipt', 'invoice', 'ticket', 'coupon', 'voucher', 'certificate', 'diploma',
             'degree', 'medal', 'trophy', 'ribbon', 'badge', 'button', 'sticker', 'seal', 'stamp', 'coin', 'currency',
             'bill', 'check', 'card', 'passport', 'id', 'license', 'permit', 'tag', 'key', 'lock', 'chain', 'ring',
             'necklace', 'bracelet', 'watch', 'earring', 'brooch', 'pin', 'badge', 'medal', 'pendant', 'charm', 'bead',
             'jewelry', 'gem', 'stone', 'diamond', 'crystal', 'gold', 'silver', 'bronze', 'metal', 'plastic', 'glass',
             'ceramic', 'porcelain', 'clay', 'wood', 'paper', 'cloth', 'fabric', 'leather', 'fur', 'feather', 'wool',
             'cotton', 'silk', 'nylon', 'polyester', 'acrylic', 'linen', 'lace', 'velvet', 'satin', 'chiffon', 'denim',
             'corduroy', 'tweed', 'flannel', 'knit', 'crochet', 'embroidery', 'beadwork', 'quilt', 'patchwork',
             'tapestry', 'rug', 'carpet', 'mat', 'tile', 'brick', 'stone', 'rock', 'pebble', 'gravel', 'sand', 'dirt',
             'mud', 'clay', 'cement', 'concrete', 'asphalt', 'tar', 'paint', 'varnish', 'stain', 'dye', 'ink',
             'pigment', 'powder', 'paste', 'gel', 'cream', 'lotion', 'oil', 'salt', 'grease', 'wax', 'resin', 'glue',
             'adhesive', 'tape', 'sealant', 'solvent', 'detergent', 'bleach', 'ammonia', 'vinegar', 'aroma', 'perfume', 'cologne',
             'deodorant', 'antiperspirant', 'soap', 'shampoo', 'conditioner', 'gel', 'mousse', 'spray']
print(len(OOD_NOUNS))
#
# list_a = ['abc']
# list_a.extend(OOD_NOUNS)
# print(len(list_a))
